name: coffee_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  firebase_auth: ^4.19.1
  google_sign_in: ^6.2.1
  firebase_core: ^2.29.0
  firebase_database: ^10.5.5
  cloud_firestore: ^4.17.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.3 
  cached_network_image: ^3.3.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/apple.png
    - assets/images/facebook.png
    - assets/images/bottom_cap.PNG
    - assets/images/get_started.png
    - assets/images/google.png
    - assets/images/top_cap.PNG
    - assets/images/top_cap2.PNG
    - assets/images/user_photo.png
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
        - asset: assets/fonts/Sora-ExtraLight.ttf
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Medium.ttf
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-SemiBold.ttf
        - asset: assets/fonts/Sora-Thin.ttf
